[package]
name = "surkaa-pad"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "surkaa_pad_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
# Tauri Store 插件 (用于持久化存储)
tauri-plugin-store = "2"
serde = { version = "1", features = ["derive"] }
argon2 = "0.5"
# AES-GCM 加密库
aes-gcm = "0.10"
# 一个通用的 AEAD 接口
aead = "0.5"
hmac = "0.12"
aliyun-oss-client = "0.13.0-alpha9"
tokio = "1.48.0" # 异步运行时
serde_json = "1.0.145" # 用于 JSON 处理
chrono = "0.4.42" # 用于获取时间戳
uuid = { version = "1.18.1", features = ["v4"] } # 用于生成唯一标识符
# 用于加载环境变量
dotenvy = "0.15.7"
tauri-plugin-fs = "2.4.4"
md5 = "0.8.0"
tauri-plugin-log = "2"
reqwest = {version ="^0.12", default-features = false, features = ["rustls-tls", "json", "stream"] }
futures = "0.3"
tauri-plugin-os = "2.3.2"

[patch.crates-io]
aliyun-oss-client = { path = "../vendor/aliyun-oss-client-modified" }
