[package]
name = "surkaa-pad"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "surkaa_pad_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
# Tauri Store 插件 (用于持久化存储)
tauri-plugin-store = "2"
serde = { version = "1", features = ["derive"] }
argon2 = "0.5"
# AES-GCM 加密库
aes-gcm = "0.10"
# 用于生成随机数 (如 IV)
rand = "0.8"
# 一个通用的 AEAD 接口
aead = "0.5"
sha2 = "0.10.9"
hmac = "0.12"
rusqlite = { version = "0.31", features = ["bundled"] }
jieba-rs = "0.8.1"
digest = "0.10.7"
aliyun-oss-client = "0.13.0-alpha9"
tokio = "1.48.0" # 异步运行时
thiserror = "2.0.17" # 用于错误处理
serde_json = "1.0.145" # 用于 JSON 处理
chrono = "0.4.42" # 用于获取时间戳
uuid = { version = "1.18.1", features = ["v4"] } # 用于生成唯一标识符

[patch.crates-io]
aliyun-oss-client = { path = "../vendor/aliyun-oss-client-modified" }
