
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * 解锁加密管理器
 * # Arguments
 * * `master_password` - 主密码
 * * `salt` - 盐值
 * # Returns
 * * `Result<(), String>` - 成功时返回 Ok，失败时返回错误信息
 */
async unlock(masterPassword: string, salt: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unlock", { masterPassword, salt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 加密数据
 * # Arguments
 * * `data` - 待加密的数据
 * # Returns
 * * `Result<(Vec<u8>, Vec<u8>), String>` - 成功时返回 (密文, nonce)，失败时返回错误信息
 */
async encryptData(data: string) : Promise<Result<[number[], number[]], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("encrypt_data", { data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 解密数据
 * # Arguments
 * * `ciphertext` - 密文
 * * `nonce` - 解密用的 nonce
 * # Returns
 * * `Result<Vec<u8>, String>` - 成功时返回明文，失败时返回错误信息
 */
async decryptData(ciphertext: number[], nonce: number[]) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("decrypt_data", { ciphertext, nonce }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 初始化 OSS 客户端
 * # Arguments
 * * `akid` - 访问密钥 ID
 * * `aks` - 访问密钥 Secret
 * * `bucket` - 存储桶名称
 * * `endpoint` - OSS 端点
 * # Returns
 * * `Result<(), String>` - 成功时返回 Ok，失败时返回错误信息
 */
async initOssClient(akid: string, aks: string, bucket: string, endpoint: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("init_oss_client", { akid, aks, bucket, endpoint }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 列出本地缓存的日记列表
 * # Arguments
 * 无需手动传参数
 * # Returns
 * * `Result<Vec<DiaryManifest>, String>` - 成功时返回日记列表，失败时返回错误信息
 */
async listLocalDiaries() : Promise<Result<DiaryManifest[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_local_diaries") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 从 OSS 同步日记到本地缓存
 * # Arguments
 * * `uuid` - 可选的日记 UUID，若提供则只同步该日记，否则同步所有日记
 * # Returns
 * * `Result<Option<DiaryManifest>, String>` - 如果传入了 UUID，成功时返回该日记的清单，否则返回 None；失败时返回错误信息
 */
async syncFromOss(uuid: string | null) : Promise<Result<DiaryManifest | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sync_from_oss", { uuid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 根据日记内容搜索日记
 * # Arguments
 * * `keyword` - 搜索关键词
 * # Returns
 * * `Result<Vec<DiaryManifest>, String>` - 成功时返回匹配的日记列表，失败时返回错误信息
 */
async searchDiaries(keyword: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_diaries", { keyword }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 根据内容保存日记
 * # Arguments
 * * `content` - 日记内容
 * # Returns
 * * `Result<String, String>` - 成功时返回日记 UUID，失败时返回错误信息
 */
async saveDiary(content: string) : Promise<Result<DiaryManifest, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_diary", { content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 更新日记的内容
 * # Arguments
 * * `uuid` - 日记 UUID
 * * `new_content` - 新的日记内容
 * # Returns
 * * `Result<(), String>` - 成功时返回 Ok，失败时返回错误信息
 */
async updateDiaryContentOnly(uuid: string, newContent: string) : Promise<Result<DiaryManifest, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_diary_content_only", { uuid, newContent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 删除日记
 * # Arguments
 * * `uuid` - 日记 UUID
 * # Returns
 * * `Result<(), String>` - 成功时返回 Ok，失败时返回错误信息
 */
async deleteDiary(uuid: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_diary", { uuid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 添加附件
 * # Arguments
 * * `uuid` - 日记 UUID
 * * `access_str` - 文件访问路径。
 * * `mimetype` - 附件 MIME 类型
 * # Returns
 * * `Result<(), String>` - 成功时返回 Ok，失败时返回错误信息
 */
async addAttachment(uuid: string, accessStr: string, mimetype: string) : Promise<Result<DiaryManifest, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_attachment", { uuid, accessStr, mimetype }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 下载附件
 * # Arguments
 * * `uuid` - 日记 UUID
 * * `filename` - 附件 ID
 * * `nonce` - 解密iv
 * # Returns
 * * `Result<Vec<u8>, String>` - 成功时返回附件字节数据，失败时返回错误信息
 */
async downloadAttachment(onEvent: TAURI_CHANNEL<DownloadAttachmentEvent>, uuid: string, filename: string, nonce: number[]) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_attachment", { onEvent, uuid, filename, nonce }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 取消任务
 * # Arguments
 * * `cancel_token` - 任务取消令牌
 * # Returns
 * * `Result<bool, String>` - 成功时返回 Ok，失败时返回错误信息
 */
async cancelTask(cancelToken: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_task", { cancelToken }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 删除附件
 * # Arguments
 * * `uuid` - 日记 UUID
 * * `filename` - 附件 ID
 * # Returns
 * * `Result<(), String>` - 成功时返回 Ok，失败时返回错误信息
 */
async deleteAttachment(uuid: string, filename: string) : Promise<Result<DiaryManifest, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_attachment", { uuid, filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 生物解锁，传入dek解锁
 * # Arguments
 * * `dek` - 数据加密密钥
 * # Returns
 * * `Result<(), String>` - 成功时返回 Ok，失败时返回错误信息
 */
async biometricUnlock(dek: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("biometric_unlock", { dek }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AttachmentMeta = { filename: string; mimetype: string; size: number; nonce: number[] }
export type DiaryManifest = { id: string; algorithm: string; content: string; created: number; updated: number; attachments: AttachmentMeta[] }
export type DownloadAttachmentEvent = { event: "started"; data: { totalSize: number } } | { event: "downloadProgress"; data: { downloaded: number } } | { event: "decrypting" } | { event: "decrypted"; data: { decryptedSize: number } } | { event: "completed"; data: { filePath: string } } | { event: "error"; data: { message: string } }
export type TAURI_CHANNEL<TSend> = null

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
