// @ts-nocheck
/* eslint-disable */

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * 解锁加密管理器
 * # Arguments
 * * `master_password` - 主密码
 * * `salt` - 盐值
 * # Returns
 * * `Result<(), String>` - 成功时返回 Ok，失败时返回错误信息
 */
async cmdUnlock(masterPassword: string, salt: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_unlock", { masterPassword, salt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 加密数据
 * # Arguments
 * * `data` - 待加密的数据
 * # Returns
 * * `Result<(Vec<u8>, Vec<u8>), String>` - 成功时返回 (密文, nonce)，失败时返回错误信息
 */
async cmdEncryptData(data: string) : Promise<Result<[number[], number[]], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_encrypt_data", { data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 解密数据
 * # Arguments
 * * `ciphertext` - 密文
 * * `nonce` - 解密用的 nonce
 * # Returns
 * * `Result<Vec<u8>, String>` - 成功时返回明文，失败时返回错误信息
 */
async cmdDecryptData(ciphertext: number[], nonce: number[]) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_decrypt_data", { ciphertext, nonce }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 生物解锁，传入dek解锁
 * # Arguments
 * * `dek` - 数据加密密钥
 * # Returns
 * * `Result<(), String>` - 成功时返回 Ok，失败时返回错误信息
 */
async cmdBiometricUnlock(dek: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_biometric_unlock", { dek }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 初始化 OSS 客户端
 * # Arguments
 * * `akid` - 访问密钥 ID
 * * `aks` - 访问密钥 Secret
 * * `bucket` - 存储桶名称
 * * `endpoint` - OSS 端点
 * # Returns
 * * `Result<(), String>` - 成功时返回 Ok，失败时返回错误信息
 */
async cmdInitOssClient(akid: string, aks: string, bucket: string, endpoint: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_init_oss_client", { akid, aks, bucket, endpoint }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 根据内容保存日记
 * # Arguments
 * * `content` - 日记内容
 * # Returns
 * * `Result<(DiarySummary, String), String>` - 成功时返回日记 Summary 和日记 ID，失败时返回错误信息
 */
async cmdSaveDiary(content: string) : Promise<Result<[DiarySummary, string], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_save_diary", { content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 更新日记的内容
 * # Arguments
 * * `id` - 日记ID
 * * `new_content` - 新的日记内容
 * # Returns
 * * `Result<(), String>` - 成功时返回 Ok，失败时返回错误信息
 */
async cmdUpdateDiaryContentOnly(id: string, newContent: string) : Promise<Result<DiarySummary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_update_diary_content_only", { id, newContent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 删除日记及其所有附件
 * # Arguments
 * * `id` - 日记ID
 * # Returns
 * * `Result<(), String>` - 成功时返回 Ok，失败时返回错误信息
 */
async cmdDeleteDiary(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_delete_diary", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 分页列出diary主键列表
 * # Arguments
 * * `count` - 每页的数量
 * * `next_token` - 分页的token
 * # Returns
 * * `Vec<String>` - diary主键列表
 */
async cmdPageDiaryIds(nextToken: string | null) : Promise<Result<[string[], string | null], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_page_diary_ids", { nextToken }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 获取日记Summary
 * # Arguments
 * * `id` - 日记ID
 * # Returns
 * * `Result<DiarySummary, String>` - 成功时返回日记 Summary，失败时返回错误信息
 */
async cmdGetDiarySummary(id: string) : Promise<Result<DiarySummary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_get_diary_summary", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 获取日记内容
 * # Arguments
 * * `id` - 日记ID
 * # Returns
 * * `Result<String, String>` - 成功时返回日记内容，失败时返回错误信息
 */
async cmdGetDiaryContent(id: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_get_diary_content", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 搜索日记
 * # Arguments
 * * `keyword` - 搜索关键词，可通过空格分隔多个关键词
 * # Returns
 * * `Result<String, String>` - 成功时返回搜索任务token，可用于取消搜索任务，失败时返回错误信息
 */
async cmdSearchDiaries(event: TAURI_CHANNEL<SearchDiariesEvent>, keyword: string, or: boolean) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_search_diaries", { event, keyword, or }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 给日记添加附件
 * # Arguments
 * * `id` - 日记 ID
 * * `access_str` - 文件访问路径。
 * * `encrypted` - 是否需要加密
 * # Returns
 * * `Result<String, String>` - 成功时返回取消Token，失败时返回错误信息
 */
async cmdAddAttachment(event: TAURI_CHANNEL<AddAttachmentEvent>, id: string, accessStr: string, encrypted: boolean) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_add_attachment", { event, id, accessStr, encrypted }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 直接传字节数据给日记添加附件
 * # Arguments
 * * `id` - 日记 ID
 * * `data` - 文件字节数据
 * * `mimetype` - 附件 MIME 类型
 * * `encrypted` - 是否需要加密
 * # Returns
 * * `Result<String, String>` - 成功时返回取消Token，失败时返回错误信息
 */
async cmdAddAttachmentMemory(event: TAURI_CHANNEL<AddAttachmentEvent>, id: string, data: number[], mimetype: string, encrypted: boolean) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_add_attachment_memory", { event, id, data, mimetype, encrypted }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 删除日记的附件
 * # Arguments
 * * `id` - 日记 ID
 * * `filename` - 附件 ID
 * # Returns
 * * `Result<(), String>` - 成功时返回 Ok，失败时返回错误信息
 */
async cmdDeleteAttachment(id: string, filename: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_delete_attachment", { id, filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 拍摄图片来添加
 * # Arguments
 * * `id` - 日记 ID
 * * `encrypted` - 是否需要加密
 * # Returns
 * * `Result<String, String>` - 成功时返回取消Token，失败时返回错误信息
 */
async cmdAddImageAttachmentFromCamera(event: TAURI_CHANNEL<AddAttachmentEvent>, id: string, encrypted: boolean) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_add_image_attachment_from_camera", { event, id, encrypted }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 取消任务
 * # Arguments
 * * `cancel_token` - 任务取消令牌
 * # Returns
 * * `Result<bool, String>` - 成功时返回 Ok，失败时返回错误信息
 */
async cmdCancelTask(cancelToken: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_cancel_task", { cancelToken }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openDevtools() : Promise<void> {
    await TAURI_INVOKE("open_devtools");
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AddAttachmentEvent = { event: "started" } | 
/**
 * 0-100 的上传进度百分比
 */
{ event: "progress"; data: number } | { event: "completed"; data: AttachmentMeta } | { event: "error"; data: string }
export type AttachmentMeta = { filename: string; mimetype: string; size: number; encrypted: boolean; nonce: number[]; algorithm: EncryptionAlgorithm }
export type DiarySummary = { id: string; created: number; updated: number; 
/**
 * 日记标题，取自正文的第一行
 */
title: string; 
/**
 * 附件列表
 */
attachments: AttachmentMeta[] }
export type EncryptionAlgorithm = "AES256-GCM_v1" | "AES-256-CTR"
export type SearchDiariesEvent = { event: "match"; data: DiarySummary } | { event: "unmatch"; data: string } | { event: "finished" } | { event: "error"; data: string }
export type TAURI_CHANNEL<TSend> = null

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
