// @ts-nocheck
/* eslint-disable */

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * 解锁加密管理器
 * # Arguments
 * * `master_password` - 主密码
 * # Returns
 * * `Result<(), String>` - 成功时返回 Ok，失败时返回错误信息
 */
async cmdUnlock(masterPassword: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_unlock", { masterPassword }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 加密数据
 * # Arguments
 * * `data` - 待加密的数据
 * # Returns
 * * `Result<Vec<u8>, String>` - 成功时返回密文（包含nonce在首），失败时返回错误信息
 */
async cmdEncryptData(data: string) : Promise<Result<number[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_encrypt_data", { data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 解密数据
 * # Arguments
 * * `encrypted` - 密文
 * # Returns
 * * `Result<Vec<u8>, String>` - 成功时返回明文，失败时返回错误信息
 */
async cmdDecryptData(encrypted: number[]) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_decrypt_data", { encrypted }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 验证密码获取密钥
 * # Arguments
 * * `master_password` - 主密码
 * # Returns
 * * `Result<String, String>` - 成功时返回数据加密密钥，失败时返回错误信息
 */
async cmdValidPassword(masterPassword: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_valid_password", { masterPassword }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 生物解锁，传入dek解锁
 * # Arguments
 * * `dek` - 数据加密密钥
 * # Returns
 * * `Result<(), String>` - 成功时返回 Ok，失败时返回错误信息
 */
async cmdBiometricUnlock(dek: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_biometric_unlock", { dek }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 获取加密配置
 */
async cmdEncryptInfo() : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_encrypt_info") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 初始化 OSS 客户端
 * # Arguments
 * * `akid` - 访问密钥 ID
 * * `aks` - 访问密钥 Secret
 * * `bucket` - 存储桶名称
 * * `endpoint` - OSS 端点
 * # Returns
 * * `Result<(), String>` - 成功时返回 Ok，失败时返回错误信息
 */
async cmdInitOssClient(akid: string, aks: string, bucket: string, endpoint: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_init_oss_client", { akid, aks, bucket, endpoint }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 根据内容保存日记
 * # Arguments
 * * `content` - 日记内容
 * # Returns
 * * `Result<(DiarySummary, String), String>` - 成功时返回日记 Summary 和日记 ID，失败时返回错误信息
 */
async cmdSaveDiary(content: string) : Promise<Result<[DiarySummary, string], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_save_diary", { content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 更新日记的内容
 * # Arguments
 * * `id` - 日记ID
 * * `new_content` - 新的日记内容
 * # Returns
 * * `Result<(), String>` - 成功时返回 Ok，失败时返回错误信息
 */
async cmdUpdateDiaryContentOnly(id: string, newContent: string) : Promise<Result<DiarySummary, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_update_diary_content_only", { id, newContent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 删除日记及其所有附件
 * # Arguments
 * * `id` - 日记ID
 * # Returns
 * * `Result<(), String>` - 成功时返回 Ok，失败时返回错误信息
 */
async cmdDeleteDiary(id: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_delete_diary", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 分页列出diary主键列表
 * # Arguments
 * * `count` - 每页的数量
 * * `next_token` - 分页的token
 * # Returns
 * * `Vec<String>` - diary主键列表
 */
async cmdPageDiaryIds(nextToken: string | null) : Promise<Result<[string[], string | null], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_page_diary_ids", { nextToken }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 获取日记Summary
 * # Arguments
 * * `id` - 日记ID
 * # Returns
 * * `Result<DiarySummary, String>` - 成功时返回日记 Summary，失败时返回错误信息
 */
async cmdGetDiarySummary(id: string) : Promise<Result<DiarySummary, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_get_diary_summary", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 获取日记内容
 * # Arguments
 * * `id` - 日记ID
 * # Returns
 * * `Result<(String, HashMap<String, String>), String>` - 成功时返回日记内容和附件filename->src Map，失败时返回错误信息
 */
async cmdGetDiaryContent(id: string) : Promise<Result<[string, Partial<{ [key in string]: string }>], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_get_diary_content", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 搜索日记
 * # Arguments
 * * `keyword` - 搜索关键词，可通过空格分隔多个关键词
 * # Returns
 * * `Result<String, String>` - 成功时返回搜索任务token，可用于取消搜索任务，失败时返回错误信息
 */
async cmdSearchDiaries(event: TAURI_CHANNEL<SearchDiariesEvent>, keyword: string, or: boolean) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_search_diaries", { event, keyword, or }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 给日记添加附件
 * # Arguments
 * * `id` - 日记 ID
 * * `access_str` - 文件访问路径。
 * * `encrypted` - 是否需要加密
 * # Returns
 * * `Result<String, String>` - 成功时返回取消Token，失败时返回错误信息
 */
async cmdAddAttachment(event: TAURI_CHANNEL<AttachmentProcessEvent>, id: string, accessStr: string, encrypted: boolean, originalFilename: string | null) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_add_attachment", { event, id, accessStr, encrypted, originalFilename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 直接传字节数据给日记添加附件
 * # Arguments
 * * `id` - 日记 ID
 * * `data` - 文件字节数据
 * * `mimetype` - 附件 MIME 类型
 * * `encrypted` - 是否需要加密
 * # Returns
 * * `Result<String, String>` - 成功时返回取消Token，失败时返回错误信息
 */
async cmdAddAttachmentMemory(event: TAURI_CHANNEL<AttachmentProcessEvent>, id: string, data: number[], mimetype: string, encrypted: boolean) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_add_attachment_memory", { event, id, data, mimetype, encrypted }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 删除日记的附件
 * # Arguments
 * * `id` - 日记 ID
 * * `filename` - 附件 ID
 * # Returns
 * * `Result<(), String>` - 成功时返回 Ok，失败时返回错误信息
 */
async cmdDeleteAttachment(id: string, filename: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_delete_attachment", { id, filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 拍摄图片来添加
 * # Arguments
 * * `id` - 日记 ID
 * * `encrypted` - 是否需要加密
 * # Returns
 * * `Result<String, String>` - 成功时返回取消Token，失败时返回错误信息
 */
async cmdAddImageAttachmentFromCamera(event: TAURI_CHANNEL<AttachmentProcessEvent>, id: string, encrypted: boolean) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_add_image_attachment_from_camera", { event, id, encrypted }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 将加密的附件转成未加密的、将未加密的附件转成加密的
 * # Arguments
 * * `id` - 日记 ID
 * * `filename` - 附件 ID
 * # Returns
 * * `Result<String, String>` - 成功时返回取消Token，失败时返回错误信息
 */
async cmdToggleAttachmentEncryption(event: TAURI_CHANNEL<AttachmentProcessEvent>, id: string, filename: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_toggle_attachment_encryption", { event, id, filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 旋转图片附件 顺时针90度、逆时针90度和180度
 * # Arguments
 * * `id` - 日记 ID
 * * `filename` - 附件 ID
 * * `rotation` - 旋转角度，单位为度，支持90、-90和180
 * # Returns
 * * `Result<String, String>` - 成功时返回取消Token，失败时返回错误信息
 */
async cmdRotateImageAttachment(event: TAURI_CHANNEL<AttachmentProcessEvent>, id: string, filename: string, rotation: number) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_rotate_image_attachment", { event, id, filename, rotation }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 主动缓存云端附件到本地
 * # Arguments
 * * `id` - 日记 ID
 * * `filename` - 附件 ID
 * # Returns
 * * `Result<String, String>` - 成功时返回取消Token，失败时返回错误信息
 */
async cmdCachingAttachment(event: TAURI_CHANNEL<AttachmentProcessEvent>, id: string, filename: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_caching_attachment", { event, id, filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 让用户选择一个位置保存附近明文
 * # Arguments
 * * `id` - 日记 ID
 * * `filename` - 附件 ID
 * # Returns
 * * `Result<String, String>` - 成功时返回取消Token，失败时返回错误信息
 */
async cmdSaveDecryptAttachment(event: TAURI_CHANNEL<AttachmentProcessEvent>, id: string, filename: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_save_decrypt_attachment", { event, id, filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 重命名附件
 * # Arguments
 * * `id` - 日记 ID
 * * `old_filename` - 旧附件 ID
 * * `new_filename` - 新附件 ID
 * * `new_content`  - 新的完整内容
 * # Returns
 * * `Result<(), String>` - 成功时返回null，失败时返回错误信息
 */
async cmdUpdateAttachmentFilename(id: string, oldFilename: string, newFilename: string, newContent: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_update_attachment_filename", { id, oldFilename, newFilename, newContent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 初始化分片上传
 */
async cmdStartChunkedUpload(id: string, filename: string, mimetype: string, encrypted: boolean, totalSize: number) : Promise<Result<ChunkedUploadStartResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_start_chunked_upload", { id, filename, mimetype, encrypted, totalSize }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 上传单个分片
 */
async cmdUploadChunk(uploadToken: string, chunkIndex: number, data: number[]) : Promise<Result<ChunkedUploadChunkResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_upload_chunk", { uploadToken, chunkIndex, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 完成分片上传
 */
async cmdFinishChunkedUpload(uploadToken: string) : Promise<Result<ChunkedUploadFinishResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_finish_chunked_upload", { uploadToken }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 取消分片上传
 */
async cmdAbortChunkedUpload(uploadToken: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_abort_chunked_upload", { uploadToken }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 取消任务
 */
async cmdCancelTask(cancelToken: string) : Promise<Result<boolean, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_cancel_task", { cancelToken }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdCleanCacheFile() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_clean_cache_file") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdCleanUnusedFile() : Promise<Result<string[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_clean_unused_file") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AppError = { error_type: string; message: string }
export type AttachmentMeta = { filename: string; mimetype: string; size: number; encrypted: boolean; nonce: number[]; algorithm: EncryptionAlgorithm; etag?: string | null }
export type AttachmentProcessEvent = { event: "started" } | 
/**
 * 0-100 的上传进度百分比
 */
{ event: "progress"; data: number } | 
/**
 * 返回附件的元数据和访问URL
 */
{ event: "completed"; data: [AttachmentMeta, string] } | 
/**
 * 不返回数据但仍成功的场景
 */
{ event: "completedWithoutData" } | { event: "error"; data: string }
export type ChunkedUploadChunkResult = { partNumber: number; etag: string; uploadedBytes: number; totalBytes: number }
export type ChunkedUploadFinishResult = { attachment: AttachmentMeta; url: string }
export type ChunkedUploadStartResult = { uploadToken: string; attachmentFilename: string; nonce: number[] | null }
export type DiarySummary = { id: string; created: number; updated: number; 
/**
 * 日记标题，取自正文的第一行
 */
title: string; 
/**
 * 附件列表
 */
attachments: AttachmentMeta[] }
export type EncryptionAlgorithm = "AES256-GCM_v1" | "AES-256-CTR"
export type SearchDiariesEvent = { event: "match"; data: DiarySummary } | { event: "unmatch"; data: string } | { event: "finished" } | { event: "error"; data: string }
export type TAURI_CHANNEL<TSend> = null

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
